### ISSUE TITLE
gz-sim: world_joint.sdf

### ISSUE THREAD

**Issue by azeey-test** [gazebosim/gazebo_test_cases#1698]
## Configuration

* os: Any

## Links

* [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim9/examples/worlds/world_joint.sdf)

**Comment by Combuster54** [comment]
Interested

**Comment by Combuster54** [comment]
# Ubuntu 20.04 Noble

Starting world_joint.sdf 

```
gz sim world_joint.sdf
```
![image](https://github.com/user-attachments/assets/320a0a2f-e7c6-4c9b-81fd-606e920ec256)

The joint is already attached to the world. Also, gz topic command shows data that validates its movement.
```
gz topic -t /world/shapes/dynamic_pose/info -e
```
![image](https://github.com/user-attachments/assets/e270f498-1487-4d9d-9d98-4c0753bac1a6)

Let me know if this the correct fortmat. In order to contribute in more issues

**Comment by ahcorde** [comment]
Thank you for testing!
