### ISSUE TITLE
docs: sdf_worlds

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#28]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/harmonic/sdf_worlds)
- [Source](https://github.com/gazebosim/docs/tree/master/harmonic/sdf_worlds.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Voldivh** [comment]
Thanks for trying it out @suresh-venkate. The world file we use on this tutorial is a base .sdf file that is used extensively in different tutorials with different purposes. It was expected, on this case, to include those subsections to the code in order to accomplish the tutorial. Since the instructions and output worked as expected, I'll be closing this issue as completed.
