### ISSUE TITLE
gz-sim: shader_param.sdf

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#369]
## Setup
- Os: Ubuntu Jammy
- BuildType: Binary

## Links
- [Source](https://github.com/gazebosim/gz-sim/tree/gz-sim8/examples/worlds/shader_param.sdf)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by JACOBIN-SCTCS** [comment]
The appearance of the model is different when viewed from the RGB camera which was the expected outcome. The simulation of the sky seems to be not good( might be due to my system configuration).

https://github.com/gazebosim/gazebo_test_cases/assets/29516177/bed5cbb6-4c1c-4ba3-87e1-548b7bf4f93e


I also got the following warning in the terminal.

![shader_param](https://github.com/gazebosim/gazebo_test_cases/assets/29516177/f31d8e04-d3e4-4de6-b6ae-ae2e7d20c45f)

**Comment by iche033** [comment]
I've seen the sky issue before from other users. I think sky may not work well on certain graphics card / driver.
