### ISSUE TITLE
sdf_tutorials: Quickstart

### ISSUE THREAD

**Issue by azeey** [gazebosim/gazebo_test_cases#458]
## Setup
- Os: Ubuntu Jammy
- BuildType: Source

## Links
- [Live](http://sdformat.org/tutorials?tut=quickstart)
- [Source](https://github.com/gazebosim/sdf_tutorials/blob/master/quickstart/tutorial_2-0.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by Kartik9250** [comment]
Hey, I would like to work on this issue

**Comment by Kartik9250** [comment]
Everything is working flawlessly.
![image](https://github.com/gazebosim/gazebo_test_cases/assets/58456392/a5ebf5b6-fbb3-4ad0-be3e-38157a1a2548)

Just one suggestion, maybe we can use write `download` instead of `fetch` at the last instruction:
"You can find plenty of SDF samples to play with [here](http://models.gazebosim.org/). Just `fetch` the model.sdf of your model of choice and give it a more meaningful name. For example, running ./check_sdf on the husky.sdf file (husky/model.sdf on the site) will generate the following output:"

**Comment by Voldivh** [comment]
Thanks @Kartik9250, I'm closing this as completed and took note of the suggestion, I agree, it makes more sense to modify it to "download".
